config/routes.rb
VGCT::Application.routes.draw do
  resources :characters

  resources :players

  resources :games

  root :to => 'characters#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
  validates :name, presence: true
  mount_uploader :charpic, CharPicUploader
end

app/models/game.rb
class Game < ActiveRecord::Base
  validate :title, presence: true
  validate :description, :presence => true, :length => { :within => 1..1000 } 
end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :truename, :format => { :with => /\A(\w+\s*)+\z/, :message => "truename is improperly formatted" }
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :ok }
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :ok }
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
        Notifications.general.deliver
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
  case level
  when :notice then 'info'
  when :error then 'error'
  when :alert then 'warning'
  end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/characters/_form.html.erb
<% if @character.errors.any? %>
  <div class="alert alert-error">
    <strong><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</strong>

    <ul>
    <% @character.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="clearfix">
   <%= f.label :name, t("activerecord.attributes.character.name", :default => "Name"), :class => :label %>
  <div class="input">
    <%= f.text_field :name, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :level, t("activerecord.attributes.character.level", :default => "Level"), :class => :label %>
  <div class="input">
    <%= f.number_field :level, :class => 'number_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :charpic, t("activerecord.attributes.character.charpic", :default => "Character Image"), :class => :label %>
  <div class="input">
    <%= f.file_field :charpic, :class => 'file_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :description, t("activerecord.attributes.character.description", :default => "Description"), :class => :label %>
  <div class="input">
    <%= f.text_area :description, :class => 'text_area' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :player, t("activerecord.attributes.character.player", :default => "Player"), :class => :label %>
  <div class="input">
    <%= f.collection_select :player, Player.all, :id, :username %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :game, t("activerecord.attributes.character.game_id", :default => "Game"), :class => :label %>
  <div class="input">
    <%= f.collection_select :game, Game.all, :id, :title %>
  </div>
</div>
<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", characters_path %>
</div>

app/views/characters/edit.html.erb
<%= form_for @character, :url => character_path(@character), :html => { :class => "edit_character", :id => "edit_character" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/characters/index.html.erb
<h1>Characters</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
        <th>
      <%= t("activerecord.attributes.character.name", :default => t("activerecord.labels.name", :default => "Name")) %>
    </th>
        <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @characters.each do |character| -%>
   <tr>
    <td><%= character.id %></td>
        <td><%= link_to character.name, character_path(character) %>
    </td>
        <td><%= character.created_at %></td>
    <td>
      <%= link_to "Show", character_path(character) %>
      <%= link_to "Edit", edit_character_path(character) %>
      <%= link_to "Destroy", character_path(character), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_character_path, :class => 'btn btn-primary' %>

app/views/characters/new.html.erb
<%= form_for @character, :url => characters_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/characters/show.html.erb
<label class="label"><%= t("activerecord.attributes.character.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</label>
<p><%= @character.name %></p>

<label class="label"><%= t("activerecord.attributes.character.level", :default => t("activerecord.labels.level", :default => "Level")) %>:</label>
<p><%= @character.level %></p>

<label class="label"><%= t("activerecord.attributes.character.charpic", :default => t("activerecord.labels.charpic", :default => "Character Image")) %>:</label>
<p><%= image_tag @character.charpic_url if @character.charpic %></p>

<label class="label"><%= t("activerecord.attributes.character.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</label>
<p><%= @character.description %></p>

<label class="label"><%= t("activerecord.attributes.character.player", :default => t("activerecord.labels.player", :default => "Player")) %>:</label>
<p><%= link_to Player.find(@character.player).username, Player.find(@character.player) %></p>

<label class="label"><%= t("activerecord.attributes.character.game", :default => t("activerecord.labels.game", :default => "Game")) %>:</label>
<p><%= link_to Game.find(@character.game).title, Game.find(@character.game) %></p>

<div class="form-actions">
<%= link_to "Back", characters_path, :class => 'btn'  %>
<%= link_to "Edit", edit_character_path(@character), :class => 'btn' %>
<%= link_to "Delete", character_path(@character), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>

app/views/games/_form.html.erb
<% if @game.errors.any? %>
  <div class="alert alert-error">
    <strong><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</strong>

    <ul>
    <% @game.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="clearfix">
   <%= f.label :title, t("activerecord.attributes.game.title", :default => "Title"), :class => :label %>
  <div class="input">
    <%= f.text_field :title, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :description, t("activerecord.attributes.game.description", :default => "Description"), :class => :label %>
  <div class="input">
    <%= f.text_area :description, :class => 'text_area' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :genre, t("activerecord.attributes.game.genre", :default => "Genre"), :class => :label %>
  <div class="input">
    <%= f.text_field :genre, :class => 'text_field' %>
  </div>
</div>
<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", games_path %>
</div>

app/views/games/edit.html.erb
<%= form_for @game, :url => game_path(@game), :html => { :class => "edit_game", :id => "edit_game" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/games/index.html.erb
<h1>Games</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
        <th>
      <%= t("activerecord.attributes.game.title", :default => t("activerecord.labels.title", :default => "Title")) %>
    </th>
        <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @games.each do |game| -%>
   <tr>
    <td><%= game.id %></td>
        <td><%= link_to game.title, game_path(game) %>
    </td>
        <td><%= game.created_at %></td>
    <td>
      <%= link_to "Show", game_path(game) %>
      <%= link_to "Edit", edit_game_path(game) %>
      <%= link_to "Destroy", game_path(game), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_game_path, :class => 'btn btn-primary' %>

app/views/games/new.html.erb
<%= form_for @game, :url => games_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/games/show.html.erb
<label class="label"><%= t("activerecord.attributes.game.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</label>
<p><%= @game.title %></p>

<label class="label"><%= t("activerecord.attributes.game.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</label>
<p><%= @game.description %></p>

<label class="label"><%= t("activerecord.attributes.game.genre", :default => t("activerecord.labels.genre", :default => "Genre")) %>:</label>
<p><%= @game.genre %></p>

<div class="form-actions">
<%= link_to "Back", games_path, :class => 'btn'  %>
<%= link_to "Edit", edit_game_path(@game), :class => 'btn' %>
<%= link_to "Delete", game_path(@game), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>VGCT</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="i-bar"></span>
            <span class="i-bar"></span>
            <span class="i-bar"></span>
          </a>
          <a class="brand" href="#">VGCT</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Games", "/games"  %></li>
                <li><%= link_to "Players", "/players"  %></li>
                <li><%= link_to "Characters", "/characters"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
          <div class="row">
            <div class="span9">
            <% [:notice, :error, :alert].each do |level| %>
            <% unless flash[level].blank? %>
             <div data-alert="alert" class="alert alert-<%= flash_class(level) %> fade in">
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                <%= content_tag :p, flash[level] %>
              </div>
              <% end %>
            <% end %>
            <%= yield %>
            </div>
            <div class="span1">&nbsp;</div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                 <ul class="nav nav-list">
                    <li class="nav-header">Navigation</li>
                <li><%= link_to "Games", "/games"  %></li>
                <li><%= link_to "Players", "/players"  %></li>
                <li><%= link_to "Characters", "/characters"  %></li>
                </ul>
                <div id="about-text">ABOUT</div>
            </div>
           </div>
          </div>
        </div>

      <footer>
        <p>&copy; Amalia 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/notifications/general.text.erb
Notifications#general

<%= @greeting %>, find me in app/views/app/views/notifications/general.text.erb

app/views/players/_form.html.erb
<% if @player.errors.any? %>
  <div class="alert alert-error">
    <strong><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</strong>

    <ul>
    <% @player.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="clearfix">
   <%= f.label :username, t("activerecord.attributes.player.username", :default => "Username"), :class => :label %>
  <div class="input">
    <%= f.text_field :username, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :truename, t("activerecord.attributes.player.truename", :default => "Truename"), :class => :label %>
  <div class="input">
    <%= f.text_field :truename, :class => 'text_field' %>
  </div>
</div>

<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", players_path %>
</div>

app/views/players/edit.html.erb
<%= form_for @player, :url => player_path(@player), :html => { :class => "edit_player", :id => "edit_player" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/players/index.html.erb
<h1>Players</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
        <th>
      <%= t("activerecord.attributes.player.username", :default => t("activerecord.labels.username", :default => "Username")) %>
    </th>
        <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @players.each do |player| -%>
   <tr>
    <td><%= player.id %></td>
        <td><%= link_to player.username, player_path(player) %>
    </td>
        <td><%= player.created_at %></td>
    <td>
      <%= link_to "Show", player_path(player) %>
      <%= link_to "Edit", edit_player_path(player) %>
      <%= link_to "Destroy", player_path(player), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_player_path, :class => 'btn btn-primary' %>

app/views/players/new.html.erb
<%= form_for @player, :url => players_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/players/show.html.erb
<label class="label"><%= t("activerecord.attributes.player.username", :default => t("activerecord.labels.username", :default => "Username")) %>:</label>
<p><%= @player.username %></p>

<label class="label"><%= t("activerecord.attributes.player.truename", :default => t("activerecord.labels.truename", :default => "Truename")) %>:</label>
<p><%= @player.truename %></p>

<div class="form-actions">
<%= link_to "Back", players_path, :class => 'btn'  %>
<%= link_to "Edit", edit_player_path(@player), :class => 'btn' %>
<%= link_to "Delete", player_path(@player), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>